### ISSUE TITLE
The issue with importing a wallet.

### ISSUE THREAD

**Issue by ykky0** [BennyTheDev/pipe-wallet#1]
node pipe.mjs walletrestore <walletname> "<seedphrase>"
Why does using this command to import a wallet with a seed phrase result in addresses that are different from the P2TR addresses in the UNISAT wallet?

**Comment by BennyTheDev** [comment]
This is because upon importing, bitcoin core does not know what addresses have been generated previously and tweaks the pubkey of your priv key to generated new addresses. This is expected behavior. Nevertheless those, as well as as previous utxos for your wallet, are still yours. 

In case you are missing utxos from your wallet after import, please run this command:

/path/to/bitcoin-cli rescanblockchain

or on windows

c:/path/to/bitcoin-cli.exe rescanblockchain

This will rescan your local chain to find existing utxos matching your wallet.
This process can take some time but it's not as slow as an initial index.

**Comment by ykky0** [comment]
Thank you, this problem is solved.

**Comment by ykky0** [comment]
> 谢谢，这个问题已经解决了。

**Comment by sslisen** [comment]
> This is because upon importing, bitcoin core does not know what addresses have been generated previously and tweaks the pubkey of your priv key to generated new addresses. This is expected behavior. Nevertheless those, as well as as previous utxos for your wallet, are still yours.
> 
> In case you are missing utxos from your wallet after import, please run this command:
> 
> /path/to/bitcoin-cli rescanblockchain
> 
> or on windows
> 
> c:/path/to/bitcoin-cli.exe rescanblockchain
> 
> This will rescan your local chain to find existing utxos matching your wallet. This process can take some time but it's not as slow as an initial index.

Hello sir.
I use rescanblockchain command to rescan the blockchain, but still 0 balance.
But this address is DO have balance checking from mempool.com. 
And it is werid that if I import the address with the same seed phrase via bitcoin-cli, it will show the correct balance.

**Comment by sslisen** [comment]
> This is because upon importing, bitcoin core does not know what addresses have been generated previously and tweaks the pubkey of your priv key to generated new addresses. This is expected behavior. Nevertheless those, as well as as previous utxos for your wallet, are still yours.
> 
> In case you are missing utxos from your wallet after import, please run this command:
> 
> /path/to/bitcoin-cli rescanblockchain
> 
> or on windows
> 
> c:/path/to/bitcoin-cli.exe rescanblockchain
> 
> This will rescan your local chain to find existing utxos matching your wallet. This process can take some time but it's not as slow as an initial index.

Sir, I use rescanblockchain command to index the all blocks. The address and UTXO are not shown.
